### ISSUE TITLE
这几天用不了  无法更新订阅

### ISSUE THREAD

**Issue by zangqiourun** [zhangkaiitugithub/passcro#4]
最近几天无法更新订阅  电脑 手机和路由器上都是无法更新订阅 报错信息如图  不知道这种情况如何处理
![image](https://github.com/zhangkaiitugithub/passcro/assets/130052096/e458ffc8-914f-43db-b345-6c603635eeaa)

**Comment by zhangkaiitugithub** [comment]
电脑端用clash for windows 0.20.39或者clash verge，v2ray。手机端使用nekobox，clash meta。
